/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SdgRouteImport } from './routes/sdg'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MandiRouteImport } from './routes/mandi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SdgRoute = SdgRouteImport.update({
  id: '/sdg',
  path: '/sdg',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MandiRoute = MandiRouteImport.update({
  id: '/mandi',
  path: '/mandi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mandi': typeof MandiRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/schemes': typeof SchemesRoute
  '/sdg': typeof SdgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mandi': typeof MandiRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/schemes': typeof SchemesRoute
  '/sdg': typeof SdgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mandi': typeof MandiRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/schemes': typeof SchemesRoute
  '/sdg': typeof SdgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyze'
    | '/faq'
    | '/history'
    | '/library'
    | '/login'
    | '/mandi'
    | '/pricing'
    | '/profile'
    | '/results'
    | '/schemes'
    | '/sdg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyze'
    | '/faq'
    | '/history'
    | '/library'
    | '/login'
    | '/mandi'
    | '/pricing'
    | '/profile'
    | '/results'
    | '/schemes'
    | '/sdg'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyze'
    | '/faq'
    | '/history'
    | '/library'
    | '/login'
    | '/mandi'
    | '/pricing'
    | '/profile'
    | '/results'
    | '/schemes'
    | '/sdg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyzeRoute: typeof AnalyzeRoute
  FaqRoute: typeof FaqRoute
  HistoryRoute: typeof HistoryRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MandiRoute: typeof MandiRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  SchemesRoute: typeof SchemesRoute
  SdgRoute: typeof SdgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sdg': {
      id: '/sdg'
      path: '/sdg'
      fullPath: '/sdg'
      preLoaderRoute: typeof SdgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandi': {
      id: '/mandi'
      path: '/mandi'
      fullPath: '/mandi'
      preLoaderRoute: typeof MandiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyzeRoute: AnalyzeRoute,
  FaqRoute: FaqRoute,
  HistoryRoute: HistoryRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MandiRoute: MandiRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  SchemesRoute: SchemesRoute,
  SdgRoute: SdgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
